modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="blank_music_discs"
version="1.0.0"
displayName="Cave sound disc"
displayURL="https://modrinth.com/user/ARaspberry523"
credits=""
authors="ARaspberry523"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.blank_music_discs]]
    modId="minecraft"
    mandatory=true
    versionRange=">1.20"
    ordering="NONE"
    side="BOTH"
