name: Publish on GitHub, CurseForge & Modrinth
on: [ workflow_dispatch ]
env:                                              #Environment variables that can later be referenced using ${{ env.MINECRAFT_VERSION }}. These are useful for repeating information and allow for quick changes for new mod updates
  MINECRAFT_VERSION: 1.20.1                        
  JAVA_VERSION: 22
jobs:
  build:
    # ...
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: AANobbMI
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 394468
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: 1.0
          github-generate-changelog: true
          github-draft: false
          github-prerelease: false
          github-commitish: dev
          github-discussion: Announcements
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar

          name: Cave sound disc
          version: 1.0
          version-type: release
          changelog-file: CHANGELOG.*

          loaders: |
            forge
          game-versions: |
            > 1.20
          game-version-filter: none
          dependencies: |
          java: |
            21

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
